name: Concurrency 2
#run-name: Concurrency 2 (${{ inputs.environment }})
on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Who to greet
        options: 
        - monalisa
        - cschleiden
      environment:    
        type: environment
        

#concurrency:
  #group: ${{ github.workflow }}-${{ github.event.inputs.environment }}
  #cancel-in-progress: true
jobs:
  sleep:
    runs-on: ubuntu-latest
    steps:
      - printmsg: dispmsg
        run: echo "${{ github.event.inputs.name }}"