name: Concurrency 1
on:
  workflow_dispatch:
    inputs:
      environment:
        desription: "Environment"
        type: environment
        required: true
        
Jobs:
  sleep:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 30