name: Docker
on: [workflow_dispatch]

jobs:
  docker-job:
    runs-on: ubuntu-latest
    container: 
      image: node:20.3-alpine3.17
      # credentials
      # username
      # pwd
      env:
        API_URL: some-url.com
      ports:
        - 80
      #volumes:
      #  - vol_name:/path/in/container #named volume
      #  - /path/to/container #unonimous volume
      #  - /path/in/host:/path/in/container # mount volume
        # options: --cpus 1
    steps:
      - name: Log Node & OS Ver
        run: |
          node -v
          cat /etc/os-release
      - name: Log Env
        run: echo $API_URL
      - name: Create a file
        run: echo 'Some text' > text.txt
      - name: Container in a Step
        uses: docker://node:18.16-alpine3.17
        with:
          args: -v
      - name: Show file content
        uses: docker://node:18.16-alpine3.17
        with:
          entrypoint: cat
          args: text.txt
      - uses: actions/checkout@v3
      - name: Run a bash sript
        uses: docker://node:18.16-alpine3.17
        with:
          entrypoint: /mnt/c/GITHUB-ACTIONS/script.sh
          args: "Some string1"