name: Docker
on: [workflow_dispathc]

jobs:
  docker-job:
    runs-on: ubuntu-latest
    container: 
      image: node:20.3-alpine3.17
      # credentials
      # username
      # pwd
      env:
        API_URL: some-url.com
      ports:
        - 80
      #volumes:
      #  - vol_name:/path/in/container
      #  - /path/to/container
      #  - /path/in/host:/path/in/container
        # options: --cpus 1
    steps:
      - name: Log Node & OS Ver
        run: |
          node -v
          cat /etc/os-release
      - name: Log Env
        echo $API_URL