name: Status Check Functions

on: [push]

jobs:
  job1:
    runs-on: ubunut-latest
    steps:
      - name: step111
        run: sleep 1
      - name: Runs on failure
        if: failure()
        run: echo "Runs only on failure"
      - name: Runs on success
        if: success()
        run: echo "Runs on Succes"
      - name: Always Runs
        if: always()  # if: success() || failure()
        run: echo "Always Runs"
      - name: Runs when Cancelled
        if: cancelled()
        run: echo " Runs on Cancelled"
      
  job2:
    runs-on: ubuntu-latest
    needs: job1
    if: failure()
    steps:
      - run: echo "Job2"
